#!/usr/bin/env bash

#pgcontents init -l $DATABASE_URL --no-prompt

#mkdir -p /app/.jupyter
#cp jupyterconfig.py /app/.jupyter/jupyter_notebook_config.py

#jupyter contrib nbextension install --user
#jupyter nbextensions_configurator enable --user

#jupyter notebook
URI=`echo $VCAP_APPLICATION | jq -r .uris[]`
#jupyter notebook --no-browser --ip=* --port 8080 \
#	--NotebookApp.allow_origin=https://${URI} \
#	--NotebookApp.websocket_url=wss://${URI}:4443 \


jupyter notebook \
  	--no-browser --no-mathjax --ip=* --port $PORT \
 	--NotebookApp.allow_origin=https://${URI} \
 	--NotebookApp.websocket_url=wss://${URI}:$PORT
#jupyter notebook \
#	--no-browser --no-mathjax --ip=0.0.0.0 --port 8080 \
#	notebooks
